import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { exo2 } from "./fonts";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LevelUpReviews",
  description: "Generated by create next app",
};

interface Props {
  children: JSX.Element[] | JSX.Element;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${exo2.className}`}>
        <Navbar />
        <main>
          <div className="container">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
